---
- hosts: Jenkins
  become: yes
  remote_user: ubuntu
  become_user: root
  tasks:
    - name: Adding jenkins key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc

    - name: Adding repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Installing Jenkins
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - '*'
        - default-jdk
        - jenkins

    - name: Starting Jenkins
      systemd:
        name: jenkins
        state: started
